pipeline {
agent any
stages {
 stage('create init') {
 steps {
  sh 'cd roboshop'
  sh 'cd roboshop ;terraform init'
   }
 }
  stage(' plan') {
  steps {
   sh 'cd roboshop'
   sh 'cd roboshop;terraform plan'
    }
  }
   stage('create apply') {
    steps {
     sh 'cd roboshop'
     sh 'cd roboshop;terraform plan -auto-approve'
      }
    }
}
}