pipeline {
agent any
stages {
 stage('create init') {
 steps {
  sh 'terraform init'
   }
 }
  stage(' plan') {
  steps {
   sh 'terraform plan'
    }
  }
   stage('create apply') {
    steps {
     sh 'terraform plan -auto-approve'
      }
    }
}
}